version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.7
      - test-3.6
      - test-3.5
      - test-3.4
jobs:
  test-3.7: &test-template
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.2

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -v -U flake8
            pip install -v -U setuptools
            pip install -v -U pip
            pip install -r requirements-dev.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: linters
          command: |
            . venv/bin/activate
            SKIP=no-commit-to-branch pre-commit run -a -v

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            py.test -vv -s --cov-report=term-missing --cov-report=html
            codecov

      - store_artifacts:
          path: htmlcov
          destination: test-reports

  test-3.6:
    <<: *test-template
    docker:
      - image: circleci/python:3.6.2

  test-3.5:
    <<: *test-template
    docker:
      - image: circleci/python:3.5.3

  test-3.4:
    <<: *test-template
    docker:
      - image: circleci/python:3.4


branches:
  only:
    - master
